CREATE TABLE USER_AUTH (
  auth_no INT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(100) NOT NULL,
  auth VARCHAR(100) NOT NULL,       -- ROLE_USER, ROLE_ADMIN ...
  PRIMARY KEY (auth_no)
) COMMENT='회원권한';
