CREATE TABLE `USER` (
  USER_NO INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID VARCHAR(100) NOT NULL,
  USER_PW VARCHAR(200) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(200),
  REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) COMMENT='회원';